# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/kyber_final.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/kyber_final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/kyber_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/phi.coe
add_files C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/invphi.coe
add_files C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/phi_rev.coe
add_files C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/invphi_rev.coe
add_files C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/pwphi_rev.coe
read_verilog -library xil_defaultlib {
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/Kyber_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/Kyber_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/NTT_core_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/NTT_core_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/butterfly_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/butterfly_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/decode_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/decode_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/decode_keccak.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/encode_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/encode_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/hash_core_Client.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/hash_core_Server.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/mux4to2.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/pattern.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/reduc.v
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/Kyber_top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/Keccak1600.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/RegisterFDRE.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/Round.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/StateMachine.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/chi.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/iota.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/pi.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/rho.vhd
  C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/design_files/theta.vhd
}
read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_0/c_shift_ram_0.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_0/c_shift_ram_0_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_1/c_shift_ram_1.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_1/c_shift_ram_1_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_11/c_shift_ram_11.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_11/c_shift_ram_11_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_2/c_shift_ram_2.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_2/c_shift_ram_2_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_3/c_shift_ram_3.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_3/c_shift_ram_3_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_4/c_shift_ram_4.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_4/c_shift_ram_4_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_5/c_shift_ram_5.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_5/c_shift_ram_5_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_6/c_shift_ram_6.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_6/c_shift_ram_6_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_8/c_shift_ram_8.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_8/c_shift_ram_8_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_9/c_shift_ram_9.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/c_shift_ram_9/c_shift_ram_9_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_5/dist_mem_gen_5.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_5/dist_mem_gen_5_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_6/dist_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_6/dist_mem_gen_6_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_7/dist_mem_gen_7.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/dist_mem_gen_7/dist_mem_gen_7_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_2/fifo_generator_2.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_2/fifo_generator_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_2/fifo_generator_2_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_3/fifo_generator_3.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_3/fifo_generator_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_3/fifo_generator_3_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_4/fifo_generator_4.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_4/fifo_generator_4.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_4/fifo_generator_4_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_5/fifo_generator_5.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_5/fifo_generator_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_5/fifo_generator_5_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_7/fifo_generator_7.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_7/fifo_generator_7.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_7/fifo_generator_7_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_8/fifo_generator_8.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_8/fifo_generator_8.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_8/fifo_generator_8_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet C:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_6/fifo_generator_6.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_6/fifo_generator_6.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/2022FPGA-SOC/kyber_final/ip_files/fifo_generator_6/fifo_generator_6_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Kyber_top -part xc7a200tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Kyber_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Kyber_top_utilization_synth.rpt -pb Kyber_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
